; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:build]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
	-O3
	-Ofast
	-ffunction-sections
	-fdata-sections
	-std=gnu++2a ; Use C++20
	-D BOARD_HAS_PSRAM
	-Werror

build_unflags = -std=gnu++11 -std=gnu++14 -std=gnu++17 -Os
lib_deps =
  https://github.com/Vicara12/SlimBoy_GameBoyEmulator#master
	lovyan03/LovyanGFX
